version: '3.9'

services:

  phoenix:
    build:
      context: .
      args:
        USER_ID: "${UID}"
        GROUP_ID: "${GID}"
    container_name: caque_app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - opensearch
    environment:
      PGUSER: "${CAQUE_PGUSER}"
      PGPASSWORD: "${CAQUE_PGPASSWORD}" 
      PGDATABASE: "${CAQUE_PGDATABASE}"
      PGHOST: "${CAQUE_PGHOST}"
      PGPORT: "${CAQUE_PGPORT}"
      # DATABASE_URL: 0.0.0.0:5432
      # DATABASE_URL: "postgres://postgres@db/caque_dev"
      OPENSEARCH_URL: "http://opensearch:9200"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
      OPENAI_KEY: "${OPENAI_KEY}"
    volumes:
      - .:/app
    command: ["sh", "entrypoint.sh"]

  db:
    image: postgres:14
    container_name: caque_db
    environment:
      POSTGRES_USER: "${CAQUE_PGUSER}"
      POSTGRES_PASSWORD: "${CAQUE_PGPASSWORD}"
      POSTGRES_DB: "${CAQUE_PGDATABASE}"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: caque_opensearch
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
      - "OPENSEARCH_INITIAL_ADMIN_USERNAME="
      # Enable ML Commons conversational memory + RAG pipeline from the start
      - "plugins.ml_commons.memory_feature_enabled=true"
      - "plugins.ml_commons.rag_pipeline_feature_enabled=true"
      # Optional but often useful when working with conversational agents
      - "plugins.ml_commons.agent_framework_enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  opensearch-data:
