import Config

# Configure your database
config :caque, Caque.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("PGHOST", "localhost"),
  database: System.get_env("PGDATABASE", "caque_dev"),
  port: System.get_env("PGPORT", "5432") |> String.to_integer(),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

  # Config for responses
  config :caque, Caque.Responses,
    openai_key: System.get_env("OPENAI_KEY"),
    response_url: "https://api.openai.com/v1/responses"

  # Config for completions
  config :caque, Caque.Completions,
    openai_key: System.get_env("OPENAI_KEY"),
    completion_url: "https://api.openai.com/v1/chat/completions"

# Config for API keys
config :caque, Caque.Embeddings,
  openai_key: System.get_env("OPENAI_KEY"),
  base_url: "https://api.openai.com/v1/embeddings"

config :caque, Caque.Documents.Cluster,
  url: "http://opensearch:9200",
  username: "admin",
  password: System.get_env("OPENSEARCH_INITIAL_ADMIN_PASSWORD")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :caque, CaqueWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "QOE6B7HJEKYKqj1veEzuDJfHlTeDAV6TzgrQCgNrSlfLcMMcakvpHh0O3VYG6QJM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:caque, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:caque, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :caque, CaqueWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/caque_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :caque, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
