import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :cake, CakeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Cake.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :cake,
  book_storage_adapter: Cake.Books.Adapters.S3

# ExAws uses IAM role credentials by default — no explicit keys needed.
# Region is read from AWS_REGION or AWS_DEFAULT_REGION env vars at runtime.
config :ex_aws,
  json_codec: Jason

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
